### ISSUE TITLE
Unecessary data in Benchmark 2 powergrid

### ISSUE THREAD

**Issue by marota** [Mleyliabadi/LIPS#108]
In Benchmark 2 for power grid, we have q_or and q_ex variables (see here for instance:https://github.com/Mleyliabadi/LIPS/tree/main/reference_data/powergrid/l2rpn_case14_sandbox/Benchmark2/train ), while they are not expected as attr_y in the config file https://github.com/Mleyliabadi/LIPS/blob/main/configurations/powergrid/benchmarks/l2rpn_case14_sandbox.ini

These create a bit of unconsistency. 
I suggest that:

1.  q_or and q_ex not to appear in this dataset
2. to have a test to check consitency between configuration file and generated data

**Comment by Mleyliabadi** [comment]
- [x] The supplementary variables are removed from benchmark2 datasets. 
- [x] The test are implemented [here](https://github.com/Mleyliabadi/LIPS/blob/ml-wip-108-dataset-check/lips/tests/test_data.py#L257)
